DROP TABLE IF EXISTS properties;

CREATE TABLE properties (
    id BIGINT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    building_name VARCHAR(200),
    building_key VARCHAR(300),
    anchor_transaction_id BIGINT,
    property_type VARCHAR(20) NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    deposit BIGINT,
    monthly_rent BIGINT,
    price BIGINT,
    maintenance_fee BIGINT,
    area_m2 DECIMAL(8, 2),
    floor INT,
    total_floor INT,
    address TEXT,
    road_address TEXT,
    sido VARCHAR(20),
    sigungu VARCHAR(30),
    dong VARCHAR(30),
    legal_dong_code VARCHAR(10),
    latitude DECIMAL(10, 7),
    longitude DECIMAL(10, 7),
    geocoding_provider VARCHAR(50),
    geocoding_quality VARCHAR(30),
    geocoded_at TIMESTAMP,
    description TEXT,
    source VARCHAR(30),
    source_property_id VARCHAR(120),
    source_url TEXT,
    crawled_at TIMESTAMP,
    registered_at DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);
